config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  resources :studysessions do
  get 'join_session', 'leave_session' # on: :edit
  get 'my_sessions'
  end
  root 'studysessions#index'

end

app/models/studysession.rb
class Studysession < ActiveRecord::Base
    validates :subject, presence: true
    validates :location, presence: true
    has_many :sessionmembers
    has_many :users, through: :sessionmembers
end

app/controllers/studysessions_controller.rb
class StudysessionsController < ApplicationController
  before_action :set_studysession, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  @view_my_sessions =false; #default
  
  
  def redir
    redirect_to studysessions_url
  end  
  helper_method :redir
  
  def is_member? (sess, mem)
    userlist = sess.users
    for i in userlist
      if i == mem
        return true
      end
    end  
    return false;
  end  
  helper_method :is_member?
  
  #named is_leader instead of is_admin to avoid naming conflicts
  def is_leader? (sess, mem)
    userlist = sess.users
    firstuser = userlist[0]
      if firstuser != nil && firstuser.id == mem.id
        return true
      else 
        return false
      end  
  end  
  helper_method :is_leader?
  
  def get_leader(sess)
     userlist = sess.users
     firstuser = userlist[0]
     return firstuser
  end  
  helper_method :get_leader
    
  
  def list_members (sess)
    list = sess.users
    userstr = ""
    length = list.size
    list.each do |user|
      userstr = userstr + user.email
    end  
    return userstr
  end  
  helper_method :list_members
  
  def member_size(sess)
    list = sess.users
    len = list.size
    #str = " #{len} member(s)" 
    return len
  end
  helper_method :member_size
  
  # GET /studysessions/:studysession_id/join_session
  def join_session
    Studysession.find(params[:studysession_id]).users << current_user
    redirect_to studysessions_url
  end  
  helper_method :join_session  
  
  # GET /studysessions/:studysession_id/leave_session
  def leave_session
    Studysession.find(params[:studysession_id]).users.delete(current_user)
    redirect_to studysessions_url
  end
  helper_method :leave_session
  
  def test_multiple_members
    sess = Studysession.create(subject: 'test4', location: 'home4', description: 'des4')
   # user1 = User.create!(email: '13@example.com', password: 'password', password_confirmation: 'password', is_admin: false)
  #  user2 = User.create!(email: '14@example.com', password: 'password', password_confirmation: 'password', is_admin: false)
    sess.users << current_user
    sess.users << User.find(5)
    
  end
  helper_method :test_multiple_members
  
    #used to display only user's sessions (created or joined)
  def my_sessions
    @view_my_sessions = true;
    @mysessions = current_user.studysessions.order("lower(subject) ASC")
    
  end
  helper_method :my_sessions
  
    
  
  # GET /studysessions
  # GET /studysessions.json
  def index
    if params[:my] == 'true'
      if params[:sort] == nil
		    @studysessions = my_sessions
	    else
		    #my sessions, sorted according to parameters
		    @studysessions = Studysession.order("lower(#{params[:sort]})" + " #{params[:direction]}").all 
		    @studysessions = @studysessions.reject{|sess| !is_member?(sess, current_user)}
		  end   
	  else
		  if params[:sort] == nil
			  @studysessions = Studysession.order("lower(subject) ASC").all #default - sort alphabetically
		  else
			  @studysessions = Studysession.order("lower(#{params[:sort]})" + " #{params[:direction]}").all 	
		  end	
	  end
end	
	
	
	
		
	
	

  # GET /studysessions/1
  # GET /studysessions/1.json
  def show
  end

  # GET /studysessions/new
  def new
    @studysession = Studysession.new
  end

  # GET /studysessions/1/edit
  def edit
  end

  # POST /studysessions
  # POST /studysessions.json
  def create
    @studysession = Studysession.new(studysession_params)
    @studysession.users << current_user
    respond_to do |format|
      if @studysession.save
        format.html { redirect_to @studysession }
        format.json { render :show, status: :created, location: @studysession }
      else
        format.html { render :new }
        format.json { render json: @studysession.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studysessions/1
  # PATCH/PUT /studysessions/1.json
  def update
    respond_to do |format|
      if @studysession.update(studysession_params)
        format.html { redirect_to @studysession }
        format.json { render :show, status: :ok, location: @studysession }
      else
        format.html { render :edit }
        format.json { render json: @studysession.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studysessions/1
  # DELETE /studysessions/1.json
  def destroy
    @studysession.destroy
    respond_to do |format|
      format.html { redirect_to studysessions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_studysession
      @studysession = Studysession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def studysession_params
      params.require(:studysession).permit(:subject, :location, :description, :members)
    end
end

app/helpers/studysessions_helper.rb
module StudysessionsHelper
end

app/views/studysessions/_form.html.erb
<%= form_for(@studysession) do |f| %>
  <% if @studysession.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@studysession.errors.count, "error") %> prohibited this studysession from being saved:</h2>

      <ul class = "errorlist">
      <% @studysession.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.submit "Save Session", class: "btn btn-default" %>
  </div>
<% end %>

app/views/studysessions/edit.html.erb
<div class = "editsession">
<h1>Editing Session</h1>


<%= render 'form' %>

<%= link_to 'Show', @studysession %> |
<%= link_to 'Back', studysessions_path %>

</div>

app/views/studysessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1><center>Study Sessions at Adelphi University</center></h1>

<% if current_user == nil %>
<center><%= link_to 'View Study Sessions', new_user_session_path,class: 'btn btn-default btn-large' %></center>

<% else %>
<center>
<ul class="nav nav-pills" role="tablist">
  <li class="active"> <%= link_to 'All Sessions', studysessions_url %></li>
  <li><%= link_to 'My Sessions',  :my => 'true' %></li>
</ul>
</center>

<center>
<table class="table table-striped">
  <div class ="table-header" >
  <thead>
    <tr>
      <th><center><%= sortable 'subject' %></center></th>
      <th><center><%= sortable 'location' %></center></th>
      <th><center><%= sortable 'description' %></center></th>
      <th><center>Members</center></th>
      <th colspan="4"></th>
    </tr>
  </thead>
  </div>
<div class="tr" >
  <tbody>
    <% @studysessions.each do |studysession| %>
      <tr>
        <td><%= studysession.subject %></td>
        <td><%= studysession.location %></td>
        <td><%= studysession.description %></td>
        <td><%= member_size(studysession) %></td>
        <td><%= link_to 'View', studysession %></td>
        <% if is_leader?(studysession, current_user) || current_user.is_admin %>
        <td><%= link_to 'Edit', edit_studysession_path(studysession) %></td>
        <td><%= link_to 'Delete', studysession, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% elsif is_member?(studysession, current_user) %>
        <td><%= link_to 'Leave', studysession_leave_session_path(studysession.id) %></td>
         <td><%='     '%></td>
        <% else %>
        <td><%= link_to 'Join', studysession_join_session_path(studysession.id) %></td>
        <td><%=    '     '          %></td>
        <% end %>
       
      </tr>
    <% end %>
    
  </tbody>
  </div>
</table>

</center>

<br>

<% if current_user != nil %>
<center>
  <%= link_to  new_studysession_path, class: 'btn btn-default' do %>
  <i class="glyphicon glyphicon-plus"></i> New Session
  <% end %>
  </center>
  
  <!-- test -->
  <% @view_my_sessions = true %>
  
  
  <!-- creating a button that is a link but also bold >
 <!-- <div class = 'btn btn-default'> <a href=studysessions/new><b>New</b> </a></div> >
<% end %>

<% end %>

app/views/studysessions/new.html.erb
<div class = "newheader" >
<h1>New Session</h1>


<%= render 'form' %>
<br>
<%= link_to 'Back', studysessions_path, class: 'btn btn-default' %> 


</div>

app/views/studysessions/show.html.erb
<p id="notice"><%= notice %></p>


<center>
<table class="table table-striped">
<tr> 
	<td><%= "Subject"%></td>
	<td><%= @studysession.subject %></td>
</tr>
<tr> 
	<td><%= "Location"%></td>
	<td><%= @studysession.location %></td>
</tr>
<tr> 
	<td><%= "Description"%></td>
	<td><%= @studysession.description %></td>
</tr>
<tr> 
	<td><%= "Members"%></td>
	<td><%= member_size(@studysession) %></td>
</tr>
<tr> 
	<td><%= "Admin"%></td>
	<td><%= get_leader(@studysession).email %></td>
</tr>
<tr> 
	<td><%= "Created"%></td>
	<td><%= @studysession.created_at %></td>
</tr>
<tr> 
	<td><%= "Last Updated"%></td>
	<td><%= @studysession.updated_at %></td>
</tr>
</table>
</center>

<div class= "show-session">

<% if is_leader?(@studysession, current_user) %>
<%= link_to 'Edit', edit_studysession_path(@studysession) %> 
<%= link_to 'Delete', @studysession, method: :delete, data: { confirm: 'Are you sure?' } %>
<% elsif is_member?(@studysession, current_user) %>
<%= link_to 'Leave', studysession_leave_session_path(@studysession.id) %>
<% else %>
<%= link_to 'Join', studysession_join_session_path(@studysession.id) %>
<% end %>
<%= link_to 'Back', studysessions_path %>

</div>